services:
- postgresql
language: python
python:
  - "3.5"
env:
- FLASK=0.11.1 DB=postgres
install: "pip3 install -r requirements.txt"
before_script:
  - psql -c 'create database test;' -U postgres
script:
  - python flask_app/flask_tests/flask_tests.py