#SECURITY_PASSWORD_HASH='sha512_crypt' #plaintext
SECURITY_EMAIL_SENDER='gameplandev@gmail.com' #no-reply@localhost
SECURITY_PASSWORD_SALT=None
SECURITY_TOKEN_AUTHENTICATION_KEY='auth_token'
SECURITY_TOKEN_AUTHENTICATION_HEADER='Authentication-Token'
SECURITY_TOKEN_MAX_AGE=None
SECURITY_DEFAULT_HTTP_AUTH_REALM='Login Required'

OAUTH2_PROVIDER_ERROR_URI='oauth/errors'
OAUTH2_PROVIDER_TOKEN_EXPIRES_IN=86400
OAUTH2_PROVIDER_ENFORCE_SSL=False
SECRET_KEY=''
